#ifndef LAYOUT_MODE_H
#define LAYOUT_MODE_H

#include "main.h"

LayoutKey modeLayout[rowsCount][columnsCount] = {
  {
    { KEY_NOOP, COLOR_BLACK },
    { KEY_LAYOUT_KEYBOARD, COLOR_YELLOW },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_DELETE, COLOR_RED }
  },
  {
    { KEY_LAYOUT_MODE, COLOR_BLACK },
    { KEY_LAYOUT_MEDIA, COLOR_YELLOW },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_TAB, COLOR_AQUA }
  },
  {
    { KEY_LAYOUT_SYSTEM, COLOR_YELLOW },
    { MODIFIERKEY_SHIFT, COLOR_FUCHSIA },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_PAGE_UP, COLOR_YELLOW },
    { KEY_NOOP, COLOR_BLACK }
  },
  {
    { KEY_LAYOUT_FUNCTIONS, COLOR_YELLOW },
    { MODIFIERKEY_CTRL, COLOR_FUCHSIA },
    { MODIFIERKEY_GUI, COLOR_FUCHSIA },
    { MODIFIERKEY_ALT, COLOR_FUCHSIA },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_HOME, COLOR_YELLOW },
    { KEY_PAGE_DOWN, COLOR_YELLOW },
    { KEY_END, COLOR_YELLOW }
  }
};

#endif
