#ifndef LAYOUT_MEDIA_H
#define LAYOUT_MEDIA_H

#include "main.h"

LayoutKey mediaLayout[rowsCount][columnsCount] = {
  {
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK }
  },
  {
    { KEY_LAYOUT_MODE, COLOR_BLACK },
    { KEY_LAYOUT_MEDIA, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK }
  },
  {
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK }
  },
  {
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_HOME, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK }
  }
};

#endif
