#ifndef LAYOUT_NUMPAD_H
#define LAYOUT_NUMPAD_H

#include "main.h"

LayoutKey numpadLayout[rowsCount][columnsCount] = {
  {
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEYPAD_ASTERIX, COLOR_PURPLE },
    { KEY_7, COLOR_WHITE }, // TODO: KEYPAD_7
    { KEY_8, COLOR_WHITE }, // TODO: KEYPAD_8
    { KEY_9, COLOR_WHITE }, // TODO: KEYPAD_9
    { KEYPAD_MINUS, COLOR_PURPLE },
    { KEY_BACKSPACE, COLOR_RED }
  },
  {
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEYPAD_SLASH, COLOR_PURPLE },
    { KEY_4, COLOR_WHITE }, // TODO: KEYPAD_4
    { KEY_5, COLOR_WHITE }, // TODO: KEYPAD_5
    { KEY_6, COLOR_WHITE }, // TODO: KEYPAD_6
    { KEYPAD_PLUS, COLOR_PURPLE },
    { KEY_SPACE, COLOR_AQUA }
  },
  {
    { KEY_LAYOUT_NUMPAD, COLOR_BLACK },
    { MODIFIERKEY_SHIFT, COLOR_FUCHSIA },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_PERIOD, COLOR_PURPLE }, // TODO: KEYPAD_PERIOD
    { KEY_1, COLOR_WHITE }, // TODO: KEYPAD_1
    { KEY_2, COLOR_WHITE }, // TODO: KEYPAD_2
    { KEY_3, COLOR_WHITE }, // TODO: KEYPAD_3
    { KEY_NOOP, COLOR_BLACK },
    { KEYPAD_ENTER, COLOR_GREEN }
  },
  {
    { KEY_NOOP, COLOR_BLACK },
    { MODIFIERKEY_CTRL, COLOR_FUCHSIA },
    { MODIFIERKEY_GUI, COLOR_FUCHSIA },
    { MODIFIERKEY_ALT, COLOR_FUCHSIA },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_EQUAL, COLOR_PURPLE },
    { KEY_0, COLOR_WHITE }, // TODO: KEYPAD_0
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK }
  }
};

#endif
