#ifndef LAYOUT_SYMBOLS_H
#define LAYOUT_SYMBOLS_H

#include "main.h"

LayoutKey symbolsLayout[rowsCount][columnsCount] = {
  {
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK }
  },
  {
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK }
  },
  {
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK }
  },
  {
    { KEY_LAYOUT_SYMBOLS, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_HOME, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK }
  }
};

#endif
