#ifndef LAYOUT_FR_H
#define LAYOUT_FR_H

#include "main.h"

LayoutKey frLayout[rowsCount][columnsCount] = {
  {
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK }
  },
  {
    { KEY_LAYOUT_MODE, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK }
  },
  {
    { KEY_LAYOUT_FR, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK }
  },
  {
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_HOME, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK },
    { KEY_NOOP, COLOR_BLACK }
  }
};

#endif
