#ifndef LAYOUT_DEFAULT_H
#define LAYOUT_DEFAULT_H

#include "main.h"

LayoutKey defaultLayout[rowsCount][columnsCount] = {
  {
    { KEY_ESC, COLOR_RED },
    { KEY_LAYOUT_WINDOW_MANAGER, COLOR_YELLOW },
    { KEY_Q, COLOR_BLUE },
    { KEY_W, COLOR_BLUE },
    { KEY_E, COLOR_BLUE },
    { KEY_R, COLOR_BLUE },
    { KEY_T, COLOR_BLUE },
    { KEY_Y, COLOR_BLUE},
    { KEY_U, COLOR_BLUE },
    { KEY_I, COLOR_BLUE },
    { KEY_O, COLOR_BLUE },
    { KEY_P, COLOR_BLUE },
    { KEY_BACKSPACE, COLOR_RED }
  },
  {
    { KEY_LAYOUT_MODE, COLOR_YELLOW },
    { KEY_LAYOUT_FR, COLOR_YELLOW },
    { KEY_A, COLOR_BLUE },
    { KEY_S, COLOR_BLUE },
    { KEY_D, COLOR_BLUE },
    { KEY_F, COLOR_BLUE },
    { KEY_G, COLOR_BLUE },
    { KEY_H, COLOR_BLUE },
    { KEY_J, COLOR_BLUE },
    { KEY_K, COLOR_BLUE },
    { KEY_L, COLOR_BLUE },
    { KEY_SYMBOL_TILDE, COLOR_BLUE },
    { KEY_SPACE, COLOR_AQUA }
  },
  {
    { KEY_LAYOUT_NUMPAD, COLOR_YELLOW },
    { MODIFIERKEY_SHIFT, COLOR_FUCHSIA },
    { KEY_Z, COLOR_BLUE },
    { KEY_X, COLOR_BLUE },
    { KEY_C, COLOR_BLUE },
    { KEY_V, COLOR_BLUE },
    { KEY_B, COLOR_BLUE },
    { KEY_N, COLOR_BLUE },
    { KEY_M, COLOR_BLUE },
    { KEY_SEMICOLON, COLOR_BLUE },
    { KEY_SYMBOL_COLON, COLOR_BLUE },
    { KEY_UP, COLOR_YELLOW },
    { KEY_ENTER, COLOR_GREEN }
  },
  {
    { KEY_LAYOUT_SYMBOLS, COLOR_YELLOW },
    { MODIFIERKEY_CTRL, COLOR_FUCHSIA },
    { MODIFIERKEY_GUI, COLOR_FUCHSIA },
    { MODIFIERKEY_ALT, COLOR_FUCHSIA },
    { KEY_SYMBOL_LEFT_PARENTHESIS, COLOR_BLUE },
    { KEY_SYMBOL_RIGHT_PARENTHESIS, COLOR_BLUE },
    { KEY_LEFT_BRACKET, COLOR_BLUE },
    { KEY_RIGHT_BRACKET, COLOR_BLUE },
    { KEY_SYMBOL_AMPERSAND, COLOR_BLUE },
    { KEY_SYMBOL_QUESTION_MARK, COLOR_BLUE },
    { KEY_LEFT, COLOR_YELLOW },
    { KEY_DOWN, COLOR_YELLOW },
    { KEY_RIGHT, COLOR_YELLOW }
  }
};

#endif
